import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
import smtplib
from email.mime.text import MIMEText

def send_email_summary(to_email: str, summary: str):
    sendgrid_key = os.getenv('SENDGRID_API_KEY')
    
    # If SendGrid is configured, use it
    if sendgrid_key:
        message = Mail(
            from_email=os.getenv('FROM_EMAIL', 'noreply@salesinsightautomator.com'),
            to_emails=to_email,
            subject='Executive Sales Summary Report',
            html_content=f"<strong>Sales Summary Generated by AI</strong><br><br>{summary.replace(chr(10), '<br>')}")
        
        try:
            sg = SendGridAPIClient(sendgrid_key)
            sg.send(message)
        except Exception as e:
            # Re-raise standard exception
            raise RuntimeError(str(e))
    # Otherwise fallback to basic SMTP
    else:
        smtp_host = os.getenv('SMTP_HOST')
        smtp_port = os.getenv('SMTP_PORT', '587')
        smtp_user = os.getenv('SMTP_USER')
        smtp_pass = os.getenv('SMTP_PASS')
        from_email = os.getenv('FROM_EMAIL', 'noreply@salesinsightautomator.com')
        
        if not smtp_host or not smtp_user or not smtp_pass:
            # Just print missing email configuration for local testing,
            # this avoids exceptions if user runs without email credentials
            print("Email service not fully configured. Outputting to console:")
            print("\n================ EMAIL CONTENT ================")
            print(f"To: {to_email}")
            print(f"Subject: Executive Sales Summary Report")
            print(f"Content: \n{summary}")
            print("===============================================\n")
            return
            
        msg = MIMEText(f"Sales Summary Generated by AI\n\n{summary}")
        msg['Subject'] = 'Executive Sales Summary Report'
        msg['From'] = from_email
        msg['To'] = to_email
        
        try:
            with smtplib.SMTP(smtp_host, int(smtp_port)) as server:
                server.starttls()
                server.login(smtp_user, smtp_pass)
                server.send_message(msg)
        except Exception as e:
            raise RuntimeError(str(e))
