import sgMail from '@sendgrid/mail';
import nodemailer from 'nodemailer';

export async function sendEmailSummary(toEmail, summary) {
  const sendgridKey = process.env.SENDGRID_API_KEY;
  const fromEmail = process.env.FROM_EMAIL || 'noreply@salesinsightautomator.com';

  const htmlContent = `<strong>Sales Summary Generated by AI</strong><br><br>${summary.replace(/\n/g, '<br>')}`;
  const textContent = `Sales Summary Generated by AI\n\n${summary}`;

  if (sendgridKey) {
    sgMail.setApiKey(sendgridKey);
    const msg = {
      to: toEmail,
      from: fromEmail,
      subject: 'Executive Sales Summary Report',
      text: textContent,
      html: htmlContent,
    };
    try {
      await sgMail.send(msg);
    } catch (err) {
      throw new Error(`SendGrid Error: ${err.message}`);
    }
  } else {
    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = process.env.SMTP_PORT || 587;
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;

    if (!smtpHost || !smtpUser || !smtpPass) {
      console.log("Email service not fully configured. Outputting to console:");
      console.log("\n================ EMAIL CONTENT ================");
      console.log(`To: ${toEmail}`);
      console.log(`Subject: Executive Sales Summary Report`);
      console.log(`Content: \n${summary}`);
      console.log("===============================================\n");
      return;
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: Number(smtpPort),
      secure: Number(smtpPort) === 465, // true for 465, false for other ports
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    try {
      await transporter.sendMail({
        from: fromEmail,
        to: toEmail,
        subject: 'Executive Sales Summary Report',
        text: textContent,
        html: htmlContent,
      });
    } catch (err) {
      throw new Error(`SMTP Error: ${err.message}`);
    }
  }
}
